### ISSUE TITLE
How I can contact you by email?

### ISSUE THREAD

**Issue by Neustradamus** [arjunsk/airplay#1]
@arjunsk: How I can contact you by email?

Can I have your email address?

You can remove this ticket after sending the reply ^^

Thanks in advance.

**Comment by autoincr** [comment]
Hey @Neustradamus ,

Can we connect on LI: https://www.linkedin.com/in/arjunsk15/ ?

**Comment by Neustradamus** [comment]
I do not use LinkedIn.

Can you publish your email here, I will have the notification and you can remove the ticket.

I will contact you after it by email.

**Comment by arjunsk** [comment]
arjunsk15@gmail.com
